# --- 本番用 たたき台
services:
  backend:
    image: churn-app-back:v2.0-prd
    container_name: back-v2.0-prd
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - WORKER_COUNT=1
      - "DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    env_file:
      - ./backend/.env

  frontend:
    image: churn-app-front:v2.0-prd
    container_name: front-v2.0-prd
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env

  db:
    image: postgres:18.4
    container_name: db-v2.0-prd
    volumes:
      - postgres_data_prd:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data_prd:
    name: churn_postgres_data_prd