# --- 開発用
services:
  backend:
    image: churn-app-back:v2.0-dev
    container_name: back-v2.0-dev
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes: 
      - .:/app # コードの同期
      - /app/backend/.venv # 念のため保護
    depends_on:
      - db
    environment:
      - "DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    env_file:
      - ./backend/.env
  
  frontend:
    image: churn-app-front:v2.0-dev
    container_name: front-v2.0-dev
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    ports:
      - "5173:5173" # Vite
    volumes:
      - ./frontend:/frontend # # コードの同期
      - /frontend/node_modules # コンテナ側のnode_modulesを保護
    env_file:
      - ./frontend/.env

  db:
    image: postgres:18.4
    container_name: db-v2.0-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data_dev:
    name: churn_postgres_data_dev