# --- 本番用 たたき台
services:
  backend:
    image: churn-app-back:v1.0-prd
    container_name: back-v1.0-prd
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - WORKER_COUNT=1

  frontend:
    image: churn-app-front:v1.0-prd
    container_name: front-v1.0-prd
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"