# --- 開発用
services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile.dev
    ports: ["8000:8000"]
    volumes: 
      - .:/app # コードの同期
      - /app/backend/.venv # 念のため保護
    environment:
      - DATABASE_URL=sqlite:////app/data/churn.db # コンテナ内でのパスを指定
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    ports: ["5173:5173"] # Vite
    volumes:
      - ./frontend:/frontend # # コードの同期
      - /frontend/node_modules # コンテナ側のnode_modulesを保護