[project]
name = "churn-prediction-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.22",
    "category-encoders>=2.9.0",
    "fastapi>=0.136.3",
    "ipykernel>=7.2.0",
    "joblib>=1.5.3",
    "mlflow>=3",
    "numpy>=2.4.6",
    "pandas<3",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.50",
    "uvicorn>=0.49.0",
]

[dependency-groups]
dev = [
    "faker>=40.21.0",
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.0",
    "sdv>=1.32.1",
]

[tool.setuptools]
packages = { find = {} }

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff.lint]
ignore = [
    "B008", # FastAPIの Depends / Query におけるデフォルト値指定を許可
]
