name: Lint & Format

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Python のチェック
      - name: Run Ruff
        run: |
          pip install ruff
          ruff check .
          ruff format --check .

      # React (TypeScript) のチェック
      - name: Run ESLint
        working-directory: ./frontend
        run: |
          corepack enable
          pnpm install
          pnpm run lint